// <auto-generated />
using System;
using Cafe.Infrastructure.ETagCache.Databases.Contexts.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cafe.Infrastructure.ETagCache.Databases.Migrations.Sqlite
{
    [DbContext(typeof(ETagCacheSqliteContext))]
    [Migration("20210907163530_ETagCacheSqliteContext_Initial")]
    partial class ETagCacheSqliteContext_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Cafe.Infrastructure.ETagCache.Database.ETag", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GetResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ETagString")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("TEXT")
                        .HasColumnName("ETagString");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("BLOB");

                    b.Property<int>("SqliteVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("UrlGetResource")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId", "GetResourceId")
                        .HasName("PK_ETags_ClientIdGetResourceId");

                    b.ToTable("ETags");
                });
#pragma warning restore 612, 618
        }
    }
}
