// <auto-generated />
using System;
using Cafe.Infrastructure.ETagCache.Databases.Contexts.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cafe.Infrastructure.ETagCache.Databases.Migrations.Mssql
{
	[DbContext(typeof(ETagCacheMssqlContext))]
    partial class ETagCacheMssqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cafe.Infrastructure.ETagCache.Database.ETag", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GetResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ETagString")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)")
                        .HasColumnName("ETagString");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SqliteVersion")
                        .HasColumnType("int");

                    b.Property<string>("UrlGetResource")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("ClientId", "GetResourceId")
                        .HasName("PK_ETags_ClientIdGetResourceId");

                    b.ToTable("ETags");
                });
#pragma warning restore 612, 618
        }
    }
}
